### ISSUE TITLE
Clarify "visually apparent list"

### ISSUE THREAD

**Issue by kengdoj** [atbcb/ICTTestingBaseline#339]
https://ictbaseline.access-board.gov/13Structure/#134-test-procedure-for-visually-apparent-lists

@cliffbert - are menus created with `<li>` included?

Should it be visually apparent list **in content (not navigation)**?

**Comment by cliffbert** [comment]
"non-navigational visually apparent lists" lol

**Comment by bruce-usab** [comment]
Maybe just follow the model for Tables?  That script is not titled as "visually apparent tables" but does things that present as a table, but are not (like an image of a table).

**Comment by cliffbert** [comment]
Non-navigational-menuistic page stuff

**Comment by kengdoj** [comment]
2/1/22: agreed that menus should not be required to have list structure . The wording of how to describe this for identify content is TBD.

**Comment by cliffbert** [comment]
"Only include lists that are part of the main page content. Exclude elements such as dropdown menus and navigational lists."

**Comment by cliffbert** [comment]
This is what I drafted for the course update: 

Exclude menus or other elements that are part of the page’s navigational framework from this test unless they are part of the main content or numbered. 

Developers may use list elements to create grouped navigational items, such as menus, submenus, lists of navigation links, breadcrumbs, etc. while styling them to remove bullets or numbering and orienting the lists horizontally instead of vertically. If these navigational elements are part of the page’s navigational framework, separate from the main content, they should not be considered visually apparent lists for this test and should be excluded. However, any numbered lists or lists which are part of the main content should be included.

**Comment by kengdoj** [comment]
4/5/2022, [nextupdateafter301](https://federalist-78ccea55-7a06-447c-aabf-bd620b207b74.app.cloud.gov/preview/atbcb/icttestingbaseline/nextupdateafter301/13Structure/#134-test-procedure-for-visually-apparent-lists) updated: 13Structure.md and ChangeLog3.md

- 13.4 identify content
  - added description of visually apparent list
  - moved html to test instructions

- 13.4 Test instructions
  - added list item checks for ol and ul
  - added term and description checks for dl
